project:
  type: website
  output-dir: docs

website:
  title: "Phani Srikanth"
  description: "Phani's personal website"
  repo-url: https://github.com/binga/binga.github.io
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@phanisrikanth33"
    card-style: summary_large_image
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
        text: About
      - icon: book
        href: blog.qmd
        text: Blog
      - icon: megaphone
        href: recommendations.qmd
        text: Recommendations
    right:
      - icon: twitter
        href: https://twitter.com/phanisrikanth33
      - icon: github
        href: https://github.com/binga/
      - icon: linkedin
        href: https://www.linkedin.com/in/phanisrikanth/
      - icon: medium
        href: https://medium.com/@phanisrikanth33
      - icon: envelope
        href: mailto:phanisrikanth33@gmail.com

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true



