project:
  type: website
  output-dir: docs

website:
  title: "Phani Srikanth"
  description: "Phani's personal website"
  repo-url: https://github.com/binga/binga.github.io
  repo-actions: [edit, issue]
  open-graph: true
  google-analytics: "G-9PB6J6H4XP"
  twitter-card:
    creator: "@phanisrikanth33"
    card-style: summary_large_image
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: file-person
        href: about.qmd
        text: About
      - icon: book
        href: blog.qmd
        text: Blog
      - icon: megaphone
        href: recommendations.qmd
        text: Recommendations
    right:
      - icon: twitter
        text: Twitter
        href: https://twitter.com/phanisrikanth33
      - icon: github
        text: GitHub
        href: https://github.com/binga/
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/phanisrikanth/
      - icon: medium
        text: Medium
        href: https://medium.com/@phanisrikanth33
      - icon: clipboard-data
        text: Kaggle
        href: https://www.kaggle.com/phanisrikanth
      - icon: envelope
        text: Email
        href: mailto:phanisrikanth33@gmail.com
      - icon: medium
        text: Google Scholar
        href: https://scholar.google.com/citations?user=QW4NmcoAAAAJ

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: true

