---
title: 'Sauteed Vegetables Recipe'
author: "Phani Srikanth"
date: "2023-02-26"
categories: [cooking, clean-eating, 15-minute-recipes, 2023]
---


#### Ingredients
1. Airfryer
2. Broccoli
3. Corn
4. Beans
5. Salt
6. Black Pepper
7. Butter

#### Process
1. Preheat the Airfryer at 390F for 3 minutes.
1. Clean Broccoli with lukewarm water
2. Defrost frozen corn
3. Defrost frozen beans
4. If the beans aren't cut, feel free to cut them into small pieces.
4. Add broccoli, corn and beans into the preheated airfryer.
5. Add a small teaspoon of salt, sprinkle some black pepper and add adequate butter for taste!
6. Airfry the ingredients for 10 minutes.
7. Make sure you are tossing the vegetables in the airfryer every 3-4 minutes for crispiness.

#### Tips
1. Storing broccoli in a freezer for a long time might be a bad idea as water content will be fully squeezed out of broccoli. This will lead to dryness which is not preferable.
2. If you prefer a slightly salty taste, consider using Amul Butter for a surprisingly better taste!
3. Read step (7) again.